Repository CEOS-Developers/CEOS-BE, pull requests merged in 2023-06, with the labels that each got.

#51 [feat] FAQ 관련 기능 전체 구현
  src/main/java/ceos/backend/domain/faq/FaqController.java
  src/main/java/ceos/backend/domain/faq/domain/Faq.java
  src/main/java/ceos/backend/domain/faq/domain/FaqCategory.java
  src/main/java/ceos/backend/domain/faq/dto/.keep
  src/main/java/ceos/backend/domain/faq/dto/FaqDto.java
  src/main/java/ceos/backend/domain/faq/dto/response/GetCategoryFaqResponse.java
  src/main/java/ceos/backend/domain/faq/exception/.keep
  src/main/java/ceos/backend/domain/faq/exception/FaqErrorCode.java
  src/main/java/ceos/backend/domain/faq/exception/FaqNotFound.java
  src/main/java/ceos/backend/domain/faq/mapper/FaqMapper.java
  src/main/java/ceos/backend/domain/faq/repository/FaqRepository.java
  src/main/java/ceos/backend/domain/faq/service/.keep
  src/main/java/ceos/backend/domain/faq/service/FaqService.java
  src/main/java/ceos/backend/domain/faq/vo/FaqVo.java
  src/main/java/ceos/backend/domain/faq/vo/UpdateFaqRequest.java
Labels: 📬 API

#53 [feat] 관리자 기능 구현
  src/main/java/ceos/backend/domain/admin/AdminController.java
  src/main/java/ceos/backend/domain/admin/domain/Admin.java
  src/main/java/ceos/backend/domain/admin/domain/AdminRole.java
  src/main/java/ceos/backend/domain/admin/dto/request/GrantAuthorityRequest.java
  src/main/java/ceos/backend/domain/admin/dto/response/GetAdminsResponse.java
  src/main/java/ceos/backend/domain/admin/exception/AdminErrorCode.java
  src/main/java/ceos/backend/domain/admin/exception/InvalidAction.java
  src/main/java/ceos/backend/domain/admin/helper/AdminHelper.java
  src/main/java/ceos/backend/domain/admin/repository/AdminMapper.java
  src/main/java/ceos/backend/domain/admin/repository/AdminRepository.java
  src/main/java/ceos/backend/domain/admin/service/AdminService.java
  src/main/java/ceos/backend/domain/admin/vo/AdminBriefInfoVo.java
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
  src/main/java/ceos/backend/global/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/ceos/backend/global/config/user/AdminDetails.java
  src/main/java/ceos/backend/global/config/user/AdminDetailsService.java
  src/main/java/ceos/backend/global/error/GlobalErrorCode.java
  src/main/java/ceos/backend/global/error/exception/ForbiddenAdminException.java
Labels: 📬 API

#54 [feat] Awards 관련 기능 구현
  src/main/java/ceos/backend/domain/awards/AwardsController.java
  src/main/java/ceos/backend/domain/awards/domain/Awards.java
  src/main/java/ceos/backend/domain/awards/dto/.keep
  src/main/java/ceos/backend/domain/awards/dto/request/AwardsRequest.java
  src/main/java/ceos/backend/domain/awards/dto/response/AllAwardsResponse.java
  src/main/java/ceos/backend/domain/awards/dto/response/AwardsResponse.java
  src/main/java/ceos/backend/domain/awards/exception/.keep
  src/main/java/ceos/backend/domain/awards/exception/AwardNotFound.java
  src/main/java/ceos/backend/domain/awards/exception/AwardsErrorCode.java
  src/main/java/ceos/backend/domain/awards/mapper/AwardsMapper.java
  src/main/java/ceos/backend/domain/awards/service/.keep
  src/main/java/ceos/backend/domain/awards/service/AwardsService.java
Labels: 📬 API

#59 [fix] Swagger Patterns 수정
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
Labels: 🐞 BugFix

#63 [refactor] FAQ, Sponsor, Management 조회시 id 컬럼 추가
  src/main/java/ceos/backend/domain/faq/dto/FaqDto.java
  src/main/java/ceos/backend/domain/management/dto/ManagementDto.java
  src/main/java/ceos/backend/domain/sponsor/SponsorController.java
  src/main/java/ceos/backend/domain/sponsor/dto/SponsorDto.java
  src/main/java/ceos/backend/domain/sponsor/dto/response/GetAllSponsorsResponse.java
  src/main/java/ceos/backend/domain/sponsor/mapper/SponsorMapper.java
  src/main/java/ceos/backend/domain/sponsor/service/SponsorService.java
Labels: ♻️ Refactor

#61 [fix] Swagger 오류
  src/main/java/ceos/backend/global/config/OpenApiConfig.java
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
Labels: 🔨 Fix

#57 [feat] 지원서 엑셀 다운로드 구현
  build.gradle
  src/main/java/ceos/backend/domain/application/ApplicationController.java
  src/main/java/ceos/backend/domain/application/domain/Application.java
  src/main/java/ceos/backend/domain/application/domain/ApplicationAnswer.java
  src/main/java/ceos/backend/domain/application/domain/ApplicationInterview.java
  src/main/java/ceos/backend/domain/application/domain/QuestionCategory.java
  src/main/java/ceos/backend/domain/application/dto/response/GetCreationTime.java
  src/main/java/ceos/backend/domain/application/exception/ApplicationErrorCode.java
  src/main/java/ceos/backend/domain/application/exception/FileCreationFailed.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationExcelHelper.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/vo/ApplicantInfoVo.java
  src/main/java/ceos/backend/domain/application/vo/ApplicationDetailVo.java
  src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java
  src/main/java/ceos/backend/global/common/response/ResponseAdvicer.java
  src/test/java/ceos/backend/domain/application/service/ApplicationServiceTest.java
Labels: 📬 API

#70 [chore] recruitments api 수정
  src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java
  src/main/java/ceos/backend/domain/recruitment/dto/.keep
  src/main/java/ceos/backend/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  src/main/java/ceos/backend/domain/recruitment/dto/response/GetRecruitmentResponse.java
  src/main/java/ceos/backend/domain/recruitment/service/.gitkeep
Labels: 📌 Chore

#68 [refac] Application 리팩토링
  src/main/java/ceos/backend/domain/application/domain/Application.java
  src/main/java/ceos/backend/domain/application/domain/ApplicationQuestion.java
  src/main/java/ceos/backend/domain/application/domain/ApplicationQuestionDetail.java
  src/main/java/ceos/backend/domain/application/domain/ExplainationColor.java
  src/main/java/ceos/backend/domain/application/dto/request/CreateApplicationRequest.java
  src/main/java/ceos/backend/domain/application/dto/request/UpdateApplicationQuestion.java
  src/main/java/ceos/backend/domain/application/dto/request/UpdatePassStatus.java
  src/main/java/ceos/backend/domain/application/dto/response/GetApplicationQuestion.java
  src/main/java/ceos/backend/domain/application/exception/ApplicationErrorCode.java
  src/main/java/ceos/backend/domain/application/exception/NotMatchingQnA.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationQuestionDetailRepository.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationQuestionRepository.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/vo/QnAVo.java
  src/main/java/ceos/backend/domain/application/vo/QuestionDetailVo.java
  src/main/java/ceos/backend/domain/application/vo/QuestionListVo.java
  src/main/java/ceos/backend/domain/application/vo/QuestionVo.java
  src/main/java/ceos/backend/domain/application/vo/QuestionWithIdVo.java
  src/main/java/ceos/backend/global/config/OpenApiConfig.java
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/templates/component/title.html
  src/main/resources/templates/static/image/CEOSlogo.png
Labels: ♻️ Refactor

#71 [Add] awards api 수정
  src/main/java/ceos/backend/domain/awards/AwardsController.java
  src/main/java/ceos/backend/domain/awards/dto/response/AllAwardsResponse.java
  src/main/java/ceos/backend/domain/awards/dto/response/GenerationAwardsResponse.java
  src/main/java/ceos/backend/domain/awards/helper/AwardsHelper.java
  src/main/java/ceos/backend/domain/awards/mapper/AwardsMapper.java
  src/main/java/ceos/backend/domain/awards/repository/AwardsRepository.java
  src/main/java/ceos/backend/domain/awards/service/AwardsService.java
  src/main/java/ceos/backend/domain/awards/vo/ProjectInfoVo.java
  src/main/java/ceos/backend/domain/project/repository/ProjectRepository.java
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
Labels: 📬 API

#72 [feat] Activity 기능 수정
  src/main/java/ceos/backend/domain/activity/ActivityController.java
  src/main/java/ceos/backend/domain/activity/converter/ActivityConverter.java
  src/main/java/ceos/backend/domain/activity/dto/GetAllActivitiesResponse.java
  src/main/java/ceos/backend/domain/activity/service/ActivityService.java
Labels: 📬 API
