Repository CEOS-Developers/CEOS-BE, pull requests merged in 2023-05, with the labels that each got.

#3 [feat] response 커스텀
  build.gradle
  src/main/java/ceos/backend/domain/example/ExampleController.java
  src/main/java/ceos/backend/domain/example/domain/.keep
  src/main/java/ceos/backend/domain/example/dto/.keep
  src/main/java/ceos/backend/domain/example/exception/.keep
  src/main/java/ceos/backend/domain/example/repository/.keep
  src/main/java/ceos/backend/domain/example/service/.keep
  src/main/java/ceos/backend/global/common/response/ResponseAdvicer.java
  src/main/java/ceos/backend/global/common/response/SuccessResponse.java
  src/main/java/ceos/backend/global/config/.keep
  src/main/java/ceos/backend/infra/.keep
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙ Setting

#5 [feat] 공통 에러 처리 셋팅
  src/main/java/ceos/backend/domain/example/ExampleController.java
  src/main/java/ceos/backend/domain/example/exception/.keep
  src/main/java/ceos/backend/domain/example/exception/ExampleErrorCode.java
  src/main/java/ceos/backend/domain/example/exception/ExampleNotFoundException.java
  src/main/java/ceos/backend/global/common/dto/ErrorReason.java
  src/main/java/ceos/backend/global/error/BaseErrorCode.java
  src/main/java/ceos/backend/global/error/BaseErrorException.java
  src/main/java/ceos/backend/global/error/ErrorResponse.java
  src/main/java/ceos/backend/global/error/GlobalErrorCode.java
  src/main/java/ceos/backend/global/error/GlobalExceptionHandler.java
  src/main/java/ceos/backend/global/error/exception/ExampleGlobalNotFoundException.java
Labels: ⚙ Setting

#6 [feat] Security 설정
  build.gradle
  src/main/java/ceos/backend/global/config/.keep
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
  src/main/java/ceos/backend/global/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ceos/backend/global/config/jwt/JwtExceptionHandlerFilter.java
  src/main/java/ceos/backend/global/config/jwt/TokenProvider.java
  src/main/java/ceos/backend/global/config/user/CustomUserDetails.java
  src/main/java/ceos/backend/global/config/user/CustomUserDetailsService.java
  src/main/java/ceos/backend/global/error/GlobalErrorCode.java
  src/main/java/ceos/backend/global/error/exception/TokenValidateException.java
Labels: ⚙ Setting

#11 [feat] 에러 slack 알림 구현
  build.gradle
  src/main/java/ceos/backend/BackendApplication.java
  src/main/java/ceos/backend/domain/example/ExampleController.java
  src/main/java/ceos/backend/domain/example/dto/.keep
  src/main/java/ceos/backend/domain/example/dto/SlackTest.java
  src/main/java/ceos/backend/global/common/dto/SlackErrorMessage.java
  src/main/java/ceos/backend/global/common/event/Event.java
  src/main/java/ceos/backend/global/common/event/EventConfig.java
  src/main/java/ceos/backend/global/common/filter/MultiReadInputStream.java
  src/main/java/ceos/backend/global/common/filter/MultiReadInputStreamFilter.java
  src/main/java/ceos/backend/global/common/helper/SpringEnvironmentHelper.java
  src/main/java/ceos/backend/global/common/response/ResponseAdvicer.java
  src/main/java/ceos/backend/global/error/GlobalExceptionHandler.java
  src/main/java/ceos/backend/infra/.keep
  src/main/java/ceos/backend/infra/slack/SlackHelper.java
  src/main/java/ceos/backend/infra/slack/SlackMessageGenerater.java
  src/main/java/ceos/backend/infra/slack/SlackSendMessageHandler.java
  src/main/resources/application.yml
Labels: ✨ Feature

#18 [feat] 배포 설정 파일 구현
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  config/nginx/Dockerfile
  config/nginx/default.conf
  config/scripts/deploy.sh
  docker-compose.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy

#19 [feat] Swagger JWT 설정
  src/main/java/ceos/backend/global/config/OpenApiConfig.java
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: ⚙ Setting

#21 [feat] 메일 서비스 구현
  build.gradle
  src/main/java/ceos/backend/domain/example/ExampleController.java
  src/main/java/ceos/backend/global/common/dto/AwsSESMail.java
  src/main/java/ceos/backend/global/common/dto/mail/CeosQuestionInfo.java
  src/main/java/ceos/backend/global/common/dto/mail/CommonQuestionInfo.java
  src/main/java/ceos/backend/global/common/dto/mail/GreetInfo.java
  src/main/java/ceos/backend/global/common/dto/mail/InterviewDateInfo.java
  src/main/java/ceos/backend/global/common/dto/mail/PartQuestionInfo.java
  src/main/java/ceos/backend/global/common/dto/mail/PersonalInfo.java
  src/main/java/ceos/backend/global/common/dto/mail/SchoolInfo.java
  src/main/java/ceos/backend/global/common/dto/mail/UuidInfo.java
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
  src/main/java/ceos/backend/infra/ses/AwsSESConfig.java
  src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java
  src/main/java/ceos/backend/infra/ses/AwsSESSendMailHandler.java
  src/main/java/ceos/backend/infra/ses/AwsSESUtils.java
  src/main/resources/templates/component/button.html
  src/main/resources/templates/component/ceosQuestionInfo.html
  src/main/resources/templates/component/commonQuestionInfo.html
  src/main/resources/templates/component/copyright.html
  src/main/resources/templates/component/divider.html
  src/main/resources/templates/component/greeting.html
  src/main/resources/templates/component/interviewDateInfo.html
  src/main/resources/templates/component/partQuestionInfo.html
  src/main/resources/templates/component/personalInfo.html
  src/main/resources/templates/component/schoolInfo.html
  src/main/resources/templates/component/title.html
  src/main/resources/templates/component/uuid.html
  src/main/resources/templates/component/uuidBox.html
  src/main/resources/templates/sendApplicationMail.html
  src/main/resources/templates/test.html
Labels: ✨ Feature

#31 [feat] 합격 확인 기능 구현 및 slack 연결
  src/main/java/ceos/backend/domain/application/ApplicationController.java
  src/main/java/ceos/backend/domain/application/domain/Application.java
  src/main/java/ceos/backend/domain/application/domain/ApplicationDetail.java
  src/main/java/ceos/backend/domain/application/domain/Interview.java
  src/main/java/ceos/backend/domain/application/domain/Pass.java
  src/main/java/ceos/backend/domain/application/domain/QuestionCategory.java
  src/main/java/ceos/backend/domain/application/dto/request/UpdateAttendanceRequest.java
  src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java
  src/main/java/ceos/backend/domain/application/exception/AlreadyCheckFinal.java
  src/main/java/ceos/backend/domain/application/exception/AlreadyCheckInterview.java
  src/main/java/ceos/backend/domain/application/exception/ApplicantNotFound.java
  src/main/java/ceos/backend/domain/application/exception/ApplicationErrorCode.java
  src/main/java/ceos/backend/domain/application/exception/NotPassDocument.java
  src/main/java/ceos/backend/domain/application/exception/NotPassFinal.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/example/exception/ExampleErrorCode.java
  src/main/java/ceos/backend/domain/settings/domain/Settings.java
  src/main/java/ceos/backend/domain/settings/exception/NotApplicationDuration.java
  src/main/java/ceos/backend/domain/settings/exception/NotDocumentResultCheckDuration.java
  src/main/java/ceos/backend/domain/settings/exception/NotFinalResultCheckDuration.java
  src/main/java/ceos/backend/domain/settings/exception/SettingsErrorCode.java
  src/main/java/ceos/backend/global/common/dto/AwsSESMail.java
  src/main/java/ceos/backend/global/common/dto/ErrorReason.java
  src/main/java/ceos/backend/global/common/dto/SlackErrorMessage.java
  src/main/java/ceos/backend/global/common/dto/SlackUnavailableReason.java
  src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/ceos/backend/global/config/jwt/JwtExceptionHandlerFilter.java
  src/main/java/ceos/backend/global/error/ErrorResponse.java
  src/main/java/ceos/backend/global/error/GlobalErrorCode.java
  src/main/java/ceos/backend/global/error/GlobalExceptionHandler.java
  src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java
  src/main/java/ceos/backend/infra/ses/AwsSESUtils.java
  src/main/java/ceos/backend/infra/slack/SlackHelper.java
  src/main/java/ceos/backend/infra/slack/SlackMessageGenerater.java
  src/main/java/ceos/backend/infra/slack/SlackSendMessageHandler.java
Labels: 📬 API

#35 [feat] 지원서 관련 변경 기능 구현
  src/main/java/ceos/backend/domain/application/ApplicationController.java
  src/main/java/ceos/backend/domain/application/domain/ApplicantInfo.java
  src/main/java/ceos/backend/domain/application/domain/Application.java
  src/main/java/ceos/backend/domain/application/domain/ApplicationQuestion.java
  src/main/java/ceos/backend/domain/application/domain/Interview.java
  src/main/java/ceos/backend/domain/application/dto/request/UpdateApplicationQuestion.java
  src/main/java/ceos/backend/domain/application/dto/request/UpdateInterviewTime.java
  src/main/java/ceos/backend/domain/application/dto/request/UpdatePassStatus.java
  src/main/java/ceos/backend/domain/application/exception/AnswerStillExist.java
  src/main/java/ceos/backend/domain/application/exception/ApplicationErrorCode.java
  src/main/java/ceos/backend/domain/application/exception/ApplicationInterviewStillExist.java
  src/main/java/ceos/backend/domain/application/exception/SamePassStatus.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationInterviewRepository.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationQuestionRepository.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/vo/QuestionVo.java
  src/main/java/ceos/backend/domain/example/ExampleController.java
  src/main/java/ceos/backend/domain/example/domain/.keep
  src/main/java/ceos/backend/domain/example/dto/SlackTest.java
  src/main/java/ceos/backend/domain/example/exception/ExampleErrorCode.java
  src/main/java/ceos/backend/domain/example/exception/ExampleNotFoundException.java
  src/main/java/ceos/backend/domain/example/repository/.keep
  src/main/java/ceos/backend/domain/example/service/.keep
  src/main/java/ceos/backend/domain/settings/domain/Settings.java
  src/main/java/ceos/backend/domain/settings/exception/AlreadyApplicationDuration.java
  src/main/java/ceos/backend/domain/settings/exception/NotDocumentPassDuration.java
  src/main/java/ceos/backend/domain/settings/exception/NotFinalPassDuration.java
  src/main/java/ceos/backend/domain/settings/exception/SettingsErrorCode.java
  src/main/java/ceos/backend/global/common/annotation/DateFormat.java
  src/main/java/ceos/backend/global/common/annotation/ValidDateList.java
  src/main/java/ceos/backend/global/common/annotation/ValidQuestionOrder.java
  src/main/java/ceos/backend/global/common/annotation/ValidTimeDuration.java
  src/main/java/ceos/backend/global/common/validator/DateListValidator.java
  src/main/java/ceos/backend/global/common/validator/DurationValidator.java
  src/main/java/ceos/backend/global/common/validator/QuestionOrderValidator.java
  src/main/java/ceos/backend/global/common/validator/TimeDurationValidator.java
  src/main/java/ceos/backend/global/util/DateTimeConvertor.java
  src/main/java/ceos/backend/global/util/InterviewDateFormatter.java
  src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java
Labels: 📬 API

#40 [feat] Management 모든 기능 구현
  src/main/java/ceos/backend/domain/management/ManagementController.java
  src/main/java/ceos/backend/domain/management/Vo/ManagementVo.java
  src/main/java/ceos/backend/domain/management/domain/Management.java
  src/main/java/ceos/backend/domain/management/domain/ManagementRole.java
  src/main/java/ceos/backend/domain/management/dto/.keep
  src/main/java/ceos/backend/domain/management/dto/ManagementDto.java
  src/main/java/ceos/backend/domain/management/dto/request/CreateManagementRequest.java
  src/main/java/ceos/backend/domain/management/dto/request/UpdateManagementRequest.java
  src/main/java/ceos/backend/domain/management/dto/response/GetAllManagementsResponse.java
  src/main/java/ceos/backend/domain/management/exception/.keep
  src/main/java/ceos/backend/domain/management/exception/ManagementErrorCode.java
  src/main/java/ceos/backend/domain/management/exception/ManagerNotFound.java
  src/main/java/ceos/backend/domain/management/helper/ManagementHelper.java
  src/main/java/ceos/backend/domain/management/mapper/ManagementMapper.java
  src/main/java/ceos/backend/domain/management/service/.keep
  src/main/java/ceos/backend/domain/management/service/ManagementService.java
  src/main/java/ceos/backend/global/common/dto/PageInfo.java
Labels: 📬 API

#37 [feat] Activity 관련 기능 구현 (1)
  src/main/java/ceos/backend/domain/activity/ActivityController.java
  src/main/java/ceos/backend/domain/activity/converter/ActivityConverter.java
  src/main/java/ceos/backend/domain/activity/domain/Activity.java
  src/main/java/ceos/backend/domain/activity/dto/.keep
  src/main/java/ceos/backend/domain/activity/dto/ActivityRequest.java
  src/main/java/ceos/backend/domain/activity/dto/ActivityResponse.java
  src/main/java/ceos/backend/domain/activity/exception/.keep
  src/main/java/ceos/backend/domain/activity/exception/ActivityErrorCode.java
  src/main/java/ceos/backend/domain/activity/exception/ActivityNotFound.java
  src/main/java/ceos/backend/domain/activity/service/.keep
  src/main/java/ceos/backend/domain/activity/service/ActivityService.java
  src/main/java/ceos/backend/domain/admin/exception/AdminErrorCode.java
  src/main/java/ceos/backend/domain/admin/exception/NotAllowedToModify.java
  src/main/java/ceos/backend/domain/settings/domain/Settings.java
  src/main/java/ceos/backend/infra/ses/AwsSESPasswordMailGenerator.java
  src/main/java/ceos/backend/infra/ses/AwsSESSendPasswordMailHandler.java
  src/test/java/ceos/backend/domain/activity/service/ActivityServiceTest.java
  src/test/java/ceos/backend/domain/settings/domain/SettingsTest.java
Labels: 📬 API

#41 [feat] 리크루팅 관련 기능 구현
  src/main/java/ceos/backend/domain/activity/service/ActivityService.java
  src/main/java/ceos/backend/domain/admin/helper/AdminHelper.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java
  src/main/java/ceos/backend/domain/recruitment/RecruitmentController.java
  src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java
  src/main/java/ceos/backend/domain/recruitment/dto/.keep
  src/main/java/ceos/backend/domain/recruitment/dto/request/UpdateRecruitmentRequest.java
  src/main/java/ceos/backend/domain/recruitment/dto/response/GetRecruitmentResponse.java
  src/main/java/ceos/backend/domain/recruitment/exception/AlreadyApplicationDuration.java
  src/main/java/ceos/backend/domain/recruitment/exception/NotApplicationDuration.java
  src/main/java/ceos/backend/domain/recruitment/exception/NotDocumentPassDuration.java
  src/main/java/ceos/backend/domain/recruitment/exception/NotDocumentResultCheckDuration.java
  src/main/java/ceos/backend/domain/recruitment/exception/NotFinalPassDuration.java
  src/main/java/ceos/backend/domain/recruitment/exception/NotFinalResultCheckDuration.java
  src/main/java/ceos/backend/domain/recruitment/exception/RecruitmentErrorCode.java
  src/main/java/ceos/backend/domain/recruitment/exception/RecruitmentNotFound.java
  src/main/java/ceos/backend/domain/recruitment/helper/RecruitmentHelper.java
  src/main/java/ceos/backend/domain/recruitment/repository/RecruitmentRepository.java
  src/main/java/ceos/backend/domain/recruitment/service/.gitkeep
  src/main/java/ceos/backend/domain/recruitment/service/RecruitmentService.java
  src/main/java/ceos/backend/domain/settings/exception/SettingsErrorCode.java
  src/main/java/ceos/backend/domain/settings/exception/SettingsNotFound.java
  src/main/java/ceos/backend/domain/settings/helper/SettingsHelper.java
  src/main/java/ceos/backend/domain/settings/repository/SettingsRepository.java
Labels: 📬 API

#42 [feat] 지원서 정보 보기 기능 구현
  src/main/java/ceos/backend/domain/admin/exception/AdminErrorCode.java
  src/main/java/ceos/backend/domain/application/ApplicationController.java
  src/main/java/ceos/backend/domain/application/dto/response/GetApplication.java
  src/main/java/ceos/backend/domain/application/dto/response/GetApplicationQuestion.java
  src/main/java/ceos/backend/domain/application/dto/response/GetApplications.java
  src/main/java/ceos/backend/domain/application/dto/response/GetInterviewTime.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationAnswerRepository.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/vo/AnswerVo.java
  src/main/java/ceos/backend/domain/application/vo/ApplicantInfoVo.java
  src/main/java/ceos/backend/domain/application/vo/ApplicationBriefInfoVo.java
  src/main/java/ceos/backend/domain/application/vo/ApplicationDetailVo.java
  src/main/java/ceos/backend/domain/application/vo/InterviewTimeVo.java
  src/main/java/ceos/backend/domain/application/vo/QnAVo.java
  src/main/java/ceos/backend/domain/application/vo/QuestionVo.java
  src/main/java/ceos/backend/infra/ses/AwsSESPasswordMailGenerator.java
  src/main/java/ceos/backend/infra/ses/AwsSESSendPasswordMailHandler.java
  src/main/resources/templates/component/interviewDateInfo.html
Labels: 📬 API

#45 [add] CORS 추가
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
Labels: 📌 Chore
