Repository CEOS-Developers/CEOS-BE, pull requests merged in 2023-07, with the labels that each got.

#74 [refac] 지원서 질문 보기 api response 변경
  src/main/java/ceos/backend/domain/application/dto/response/GetApplicationQuestion.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/vo/InterviewDateTimesVo.java
Labels: ♻️ Refactor

#76 [feat] 리프레시 토큰 구현
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/ceos/backend/domain/admin/AdminController.java
  src/main/java/ceos/backend/domain/admin/dto/request/RefreshTokenRequest.java
  src/main/java/ceos/backend/domain/admin/dto/response/TokenResponse.java
  src/main/java/ceos/backend/domain/admin/exception/AdminErrorCode.java
  src/main/java/ceos/backend/domain/admin/exception/NotRefreshToken.java
  src/main/java/ceos/backend/domain/admin/exception/RefreshTokenNotFound.java
  src/main/java/ceos/backend/domain/admin/helper/AdminHelper.java
  src/main/java/ceos/backend/domain/admin/repository/AdminMapper.java
  src/main/java/ceos/backend/domain/admin/service/AdminService.java
  src/main/java/ceos/backend/global/config/RedisConfig.java
  src/main/java/ceos/backend/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ceos/backend/global/config/jwt/TokenProvider.java
  src/main/resources/application.yml
Labels: 📬 API

#79 [add] Admin api 권한 수정
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
Labels: 📬 API, 📌 Chore

#78 [feat] application question response 변경
  src/main/java/ceos/backend/domain/application/domain/Application.java
  src/main/java/ceos/backend/domain/application/domain/ApplicationDetail.java
  src/main/java/ceos/backend/domain/application/dto/request/CreateApplicationRequest.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/vo/InterviewDateTimesVo.java
  src/main/java/ceos/backend/global/common/dto/AwsSESMail.java
  src/main/java/ceos/backend/global/common/dto/mail/CeosQuestionInfo.java
  src/main/java/ceos/backend/global/common/dto/mail/GreetInfo.java
  src/main/java/ceos/backend/global/util/DurationFormatter.java
  src/main/java/ceos/backend/global/util/ParsingDuration.java
  src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java
  src/main/java/ceos/backend/infra/ses/AwsSESSendMailHandler.java
Labels: ♻️ Refactor

#82 [feat] 파트별 운영진 조회 api 구현
  src/main/java/ceos/backend/domain/management/ManagementController.java
  src/main/java/ceos/backend/domain/management/Vo/ManagementVo.java
  src/main/java/ceos/backend/domain/management/domain/Management.java
  src/main/java/ceos/backend/domain/management/domain/ManagementPart.java
  src/main/java/ceos/backend/domain/management/domain/ManagementRole.java
  src/main/java/ceos/backend/domain/management/dto/ManagementDto.java
  src/main/java/ceos/backend/domain/management/dto/response/GetAllPartManagementsResponse.java
  src/main/java/ceos/backend/domain/management/mapper/ManagementMapper.java
  src/main/java/ceos/backend/domain/management/repository/ManagementRepository.java
  src/main/java/ceos/backend/domain/management/service/ManagementService.java
Labels: ✨ Feature

#87 [feat] application 질문 관련 response 변경
  src/main/java/ceos/backend/domain/application/dto/request/UpdateApplicationQuestion.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/vo/ApplicationBriefInfoVo.java
Labels: ♻️ Refactor

#88 [feat] application 전체보기 sorting 추가
  src/main/java/ceos/backend/domain/application/ApplicationController.java
  src/main/java/ceos/backend/domain/application/enums/SortType.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
Labels: ♻️ Refactor

#90 [fix] 에러 처리 조건 추가
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
Labels: 🐞 BugFix

#93 [fix] award 페이지에서 max generation 찾을때 project 기준으로 찾기
  src/main/java/ceos/backend/domain/project/repository/ProjectRepository.java
Labels: 🔨 Fix

#91 [refact] 지원서 전체 불러오기 sorting type 추가
  src/main/java/ceos/backend/domain/application/enums/SortType.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
Labels: ♻️ Refactor

#94 [refact] application 전체 보기 정렬 분리
  src/main/java/ceos/backend/domain/application/ApplicationController.java
  src/main/java/ceos/backend/domain/application/enums/SortPartType.java
  src/main/java/ceos/backend/domain/application/enums/SortPassType.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/repository/ApplicationRepository.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
Labels: ♻️ Refactor

#96 [refact] 페이징 필드명 content로 통일
  src/main/java/ceos/backend/domain/activity/dto/GetAllActivitiesResponse.java
  src/main/java/ceos/backend/domain/application/dto/response/GetApplications.java
  src/main/java/ceos/backend/domain/awards/dto/response/AllAwardsResponse.java
  src/main/java/ceos/backend/domain/awards/dto/response/AwardsResponse.java
  src/main/java/ceos/backend/domain/awards/service/AwardsService.java
  src/main/java/ceos/backend/domain/management/ManagementController.java
  src/main/java/ceos/backend/domain/management/dto/response/GetAllManagementsResponse.java
  src/main/java/ceos/backend/domain/project/dto/response/GetProjectsResponse.java
  src/main/java/ceos/backend/domain/sponsor/dto/response/GetAllSponsorsResponse.java
Labels: 🔨 Fix, ♻️ Refactor, 📌 Chore

#98 [refact] 인터뷰 시간 정하기 request 변경
  src/main/java/ceos/backend/domain/application/dto/request/UpdateInterviewTime.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/global/common/dto/ParsedDuration.java
  src/main/java/ceos/backend/global/util/ParsingDuration.java
  src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java
Labels: ♻️ Refactor

#99 [refact] application 리팩토링
  src/main/java/ceos/backend/domain/application/ApplicationController.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationExcelHelper.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/service/ApplicationExcelService.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/validator/ApplicationValidator.java
  src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java
  src/main/java/ceos/backend/domain/recruitment/validator/RecruitmentValidator.java
  src/main/java/ceos/backend/global/util/DateTimeConvertor.java
  src/main/java/ceos/backend/global/util/InterviewConvertor.java
  src/main/java/ceos/backend/global/util/InterviewDateTimeConvertor.java
  src/main/java/ceos/backend/global/util/ParsedDurationConvertor.java
  src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java
Labels: ♻️ Refactor

#102 [refact] awards 추가, 수정 기수별로 묶어서 한번에 요청
  src/main/java/ceos/backend/domain/awards/AwardsController.java
  src/main/java/ceos/backend/domain/awards/dto/response/AwardsResponse.java
  src/main/java/ceos/backend/domain/awards/service/AwardsService.java
Labels: ♻️ Refactor

#106 [refac] application 전체보기 response 변경
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/vo/ApplicationBriefInfoVo.java
  src/main/java/ceos/backend/global/common/dto/ParsedDuration.java
Labels: ♻️ Refactor

#107 [feat] 지원서 엑셀 파일 생성 시각 API 구현
  src/main/java/ceos/backend/domain/application/ApplicationController.java
  src/main/java/ceos/backend/domain/application/service/ApplicationExcelService.java
  src/test/java/ceos/backend/domain/application/ApplicationControllerTest.java
  src/test/java/ceos/backend/domain/application/ApplicationExcelServiceTest.java
  src/test/java/ceos/backend/domain/application/service/ApplicationServiceTest.java
Labels: 📬 API

#109 [fix] Gradle build spotless 에러
  .github/workflows/deploy.yml
  src/main/java/ceos/backend/domain/application/domain/Pass.java
  src/test/java/ceos/backend/domain/application/ApplicationControllerTest.java
  src/test/java/ceos/backend/domain/application/ApplicationExcelServiceTest.java
Labels: 🐞 BugFix

#111 [feat] sponsor 하나 조회 api 구현
  src/main/java/ceos/backend/domain/sponsor/SponsorController.java
  src/main/java/ceos/backend/domain/sponsor/service/SponsorService.java
Labels: ✨ Feature

#114 [refact] 결과 확인 response 변경
  src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
Labels: ♻️ Refactor

#120 [refact] 합격 조회 response 수정
  src/main/java/ceos/backend/domain/application/domain/ApplicantInfo.java
  src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
Labels: ♻️ Refactor
