Repository CEOS-Developers/CEOS-BE, pull requests merged in 2023-08, with the labels that each got.

#122 [feat] 서류 결과 확인하기 기능 500 해결
  src/main/java/ceos/backend/domain/application/exception/ApplicationErrorCode.java
  src/main/java/ceos/backend/domain/application/exception/NotSetInterviewTime.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/validator/ApplicationValidator.java
Labels: 🐞 BugFix

#123 [refact] 서류 결과 확인 response 변경
  src/main/java/ceos/backend/domain/application/dto/response/GetResultResponse.java
Labels: ♻️ Refactor

#126 [fix] application question 가져오기 response 변경
  src/main/java/ceos/backend/domain/application/domain/ApplicationQuestion.java
Labels: 🔨 Fix

#137 [feat] question 수정, 최종 합격 여부 조회 서비스 validation 추가
  src/main/java/ceos/backend/domain/application/domain/Application.java
  src/main/java/ceos/backend/domain/application/exception/ApplicationErrorCode.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/AlreadyCheckFinal.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/AlreadyCheckInterview.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/AnswerStillExist.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/ApplicantNotFound.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/ApplicationInterviewStillExist.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/ApplicationStillExist.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/DuplicateApplicant.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/FileCreationFailed.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/InterviewNotFound.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/NotMatchingQnA.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/NotPassDocument.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/NotPassFinal.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/NotSetInterviewTime.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/QuestionNotFound.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/SamePassStatus.java
  src/main/java/ceos/backend/domain/application/exception/exceptions/WrongGeneration.java
  src/main/java/ceos/backend/domain/application/helper/ApplicationHelper.java
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
  src/main/java/ceos/backend/domain/application/service/ApplicationExcelService.java
  src/main/java/ceos/backend/domain/application/service/ApplicationService.java
  src/main/java/ceos/backend/domain/application/validator/ApplicationValidator.java
  src/main/java/ceos/backend/domain/recruitment/domain/Recruitment.java
  src/main/java/ceos/backend/infra/ses/AwsSESMailGenerator.java
Labels: ✨ Feature

#139 [refactor] 면접 시간 정렬 추가
  src/main/java/ceos/backend/domain/application/mapper/ApplicationMapper.java
Labels: ♻️ Refactor

#143 [refact] origin 허용 임시 추가
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
Labels: ♻️ Refactor

#147 [feat] swagger 비밀번호 셋팅
  src/main/java/ceos/backend/global/common/filter/AccessDeniedFilter.java
  src/main/java/ceos/backend/global/common/helper/SpringEnvironmentHelper.java
  src/main/java/ceos/backend/global/config/WebSecurityConfig.java
  src/main/java/ceos/backend/global/config/user/AdminDetailsService.java
Labels: ✨ Feature
